
name: Build, push

on:
    release:
        types: [published]
    push:
        branches:
            - dev

    workflow_dispatch:

jobs:
    docker_amd64:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker build
              uses: docker/build-push-action@v5
              with:
                  context: .
                  tags: biohazard_image
                  load: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Nextflow setup
              uses: nf-core/setup-nextflow@v1

            - name: Nextflow test
              run: |
                nextflow run -with-docker biohazard_image biohazard.nf

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker build push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/biohazard-tools:multi_${{ github.ref_name }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64
                  push: true
