
name: Build, push

on:
    release:
        types: [created]
    pull_request:
        branches:
            - main
            
    push:
        branches:
            - dev

    workflow_dispatch:

jobs:
    docker_amd64:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker build
              uses: docker/build-push-action@v5
              with:
                  context: .
                  tags: biohazard_image
                  load: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Nextflow setup
              uses: nf-core/setup-nextflow@v1

            - name: Nextflow test of local image
              run: |
                nextflow run -with-docker biohazard_image biohazard.nf

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              if: github.ref_name != 'main'
              with:
                  username: rbiermanpu
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker build push
              uses: docker/build-push-action@v5
              if: github.ref_name != 'main'
              with:
                  context: .
                  tags: rbiermanpu/biohazard-tools:${{ github.ref_name }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64
                  push: true

            - name: Docker test of pushed image
              if: github.ref_name != 'main'
              run: |
                docker run --rm rbiermanpu/biohazard-tools:${{ github.ref_name }} bam-fixpair --help

            - name: Nextflow test of pushed image
              if: github.ref_name != 'main'
              run: |
                nextflow run -with-docker rbiermanpu/biohazard-tools:${{ github.ref_name }} biohazard.nf

            - name: Docker build and push as "latest" if performing a release
              uses: docker/build-push-action@v5
              if: github.event_name == 'release'
              with:
                  context: .
                  tags: rbiermanpu/biohazard-tools
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64
                  push: true
