
name: Build, push

on:
    release:
        types: [published]
    push:
        branches:
            - dev

    workflow_dispatch:

jobs:
    docker_amd64:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/biohazard-tools:${{ github.ref_name }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  push: true
                  platforms: linux/amd64
